name: 'Docker Metadata action'
description: "GitHub Action to extract metadata (tags, labels) for Docker"
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  context:
    description: 'Where to get context data. Allowed options are "workflow"  (default), "git".'
    default: "workflow"
    required: true
  images:
    description: 'List of Docker images to use as base name for tags'
    required: false
  tags:
    description: 'List of tags as key-value pair attributes'
    required: false
  flavor:
    description: 'Flavors to apply'
    required: false
  labels:
    description: 'List of custom labels'
    required: false
  annotations:
    description: 'List of custom annotations'
    required: false
  sep-tags:
    description: 'Separator to use for tags output (default \n)'
    required: false
  sep-labels:
    description: 'Separator to use for labels output (default \n)'
    required: false
  sep-annotations:
    description: 'Separator to use for annotations output (default \n)'
    required: false
  bake-target:
    description: 'Bake target name (default docker-metadata-action)'
    required: false
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true

outputs:
  version:
    description: 'Generated Docker image version'
    value: '${{ steps.docker-meta.outputs.version }}'
  tags:
    description: 'Generated Docker tags'
    value: '${{ steps.docker-meta.outputs.tags }}'
  tag-names:
    description: 'Generated Docker tag names without image base name'
    value: '${{ steps.docker-meta.outputs.tag-names }}'
  labels:
    description: 'Generated Docker labels'
    value: '${{ steps.docker-meta.outputs.labels }}'
  annotations:
    description: 'Generated annotations'
    value: '${{ steps.docker-meta.outputs.annotations }}'
  json:
    description: 'JSON output of tags and labels'
    value: '${{ steps.docker-meta.outputs.json }}'
  bake-file-tags:
    description: 'Bake definition file with tags'
    value: '${{ steps.docker-meta.outputs.bake-file-tags }}'
  bake-file-labels:
    description: 'Bake definition file with labels'
    value: '${{ steps.docker-meta.outputs.bake-file-labels }}'
  bake-file-annotations:
    description: 'Bake definition file with annotations'
    value: '${{ steps.docker-meta.outputs.bake-file-annotations }}'
  bake-file:
    description: 'Bake definition file with tags and labels'
    value: '${{ steps.docker-meta.outputs.bake-file }}'

runs:
  using: 'composite'
  steps:
    - name: Generate Docker metadata
      id: docker-meta
      uses: docker/metadata-action@v6
      with:
        context: ${{ inputs.context }}
        images: ${{ inputs.images }}
        tags: ${{ inputs.tags }}
        flavor: ${{ inputs.flavor }}
        labels: ${{ inputs.labels }}
        annotations: ${{ inputs.annotations }}
        sep-tags: ${{ inputs.sep-tags }}
        sep-labels: ${{ inputs.sep-labels }}
        sep-annotations: ${{ inputs.sep-annotations }}
        bake-target: ${{ inputs.bake-target }}
        github-token: ${{ inputs.github-token }}
