name: 'Docker Login'
description: 'GitHub Action to login against a Docker registry'
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: false
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: false
  ecr:
    description: 'Specifies whether the given registry is ECR (auto, true or false)'
    required: false
  scope:
    description: 'Scope for the authentication token'
    required: false
  logout:
    description: 'Log out from the Docker registry at the end of a job'
    default: 'true'
    required: false
  registry-auth:
    description: 'Raw authentication to registries, defined as YAML objects'
    required: false

runs:
  using: 'composite'
  steps:
      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v4
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}
          ecr: ${{ inputs.ecr }}
          scope: ${{ inputs.scope }}
          logout: ${{ inputs.logout }}
          registry-auth: ${{ inputs.registry-auth }}
