name: Docker Buildx Bake

on:
  workflow_call:
    inputs:
      # docker/metadata-action
      context:
        type: string
        description: 'Where to get context data. Allowed options are "workflow"  (default), "git".'
        default: "workflow"
        required: false
      images:
        type: string
        description: 'List of Docker images to use as base name for tags'
        required: false
      tags:
        type: string
        description: 'List of tags as key-value pair attributes'
        required: false
        default: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=branch
          type=sha
      flavor:
        type: string
        description: 'Flavors to apply'
        required: false
      labels:
        type: string
        description: 'List of custom labels'
        required: false
      annotations:
        type: string
        description: 'List of custom annotations'
        required: false
      sep-tags:
        type: string
        description: 'Separator to use for tags output (default \n)'
        required: false
      sep-labels:
        type: string
        description: 'Separator to use for labels output (default \n)'
        required: false
      sep-annotations:
        type: string
        description: 'Separator to use for annotations output (default \n)'
        required: false
      bake-target:
        type: string
        description: 'Bake target name (default docker-metadata-action)'
        required: false

      # docker/bake-action
      builder:
        type: string
        description: "Builder instance"
        required: false
      allow:
        type: string
        description: "Allow build to access specified resources (e.g., network.host)"
        required: false
      call:
        type: string
        description: "Set method for evaluating build (e.g., check)"
        required: false
      files:
        type: string
        description: "List of bake definition files"
        required: false
        default: './docker-bake.hcl'
      no-cache:
        type: string
        description: "Do not use cache when building the image"
        required: false
        default: 'false'
      pull:
        type: string
        description: "Always attempt to pull a newer version of the image"
        required: false
        default: 'false'
      load:
        type: string
        description: "Load is a shorthand for --set=*.output=type=docker"
        required: false
        default: 'false'
      provenance:
        type: string
        description: "Provenance is a shorthand for --set=*.attest=type=provenance"
        required: false
      push:
        type: string
        description: "Push is a shorthand for --set=*.output=type=registry"
        required: false
        default: 'false'
      sbom:
        type: string
        description: "SBOM is a shorthand for --set=*.attest=type=sbom"
        required: false
      set:
        type: string
        description: "List of targets values to override (eg. targetpattern.key=value)"
        required: false
      source:
        type: string
        description: "Context to build from. Can be either local to specify the working directory or a remote bake definition"
        required: false
      targets:
        type: string
        description: "List of bake targets"
        required: false
        default: 'default'
      vars:
        type: string
        description: "Variables to set in the Bake definition as list of key-value pair"
        required: false

      # Permissions
      permit-login:
        type: boolean
        default: false
        description: 'Permit login to container registry'
      permit-push:
        type: boolean
        default: false
        description: 'Permit pushing built images to container registry'
      permit-cache:
        type: boolean
        default: false
        description: 'Permit using GitHub Actions cache for buildx'
    secrets:
      github-token:
        description: 'GitHub token for private repositories (default: github.token)'
        required: false
      BUILDX_BAKE_GIT_AUTH_TOKEN:
        description: 'Git HTTP authentication token for remote Bake files. (default: github.token)'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v6
        with:
          context: ${{ inputs.context }}
          images: ${{ inputs.images }}
          tags: ${{ inputs.tags }}
          flavor: ${{ inputs.flavor }}
          labels: ${{ inputs.labels }}
          annotations: ${{ inputs.annotations }}
          sep-tags: ${{ inputs.sep-tags }}
          sep-labels: ${{ inputs.sep-labels }}
          sep-annotations: ${{ inputs.sep-annotations }}
          bake-target: ${{ inputs.bake-target }}

      - name: Generate GitHub metadata
        id: github-meta
        uses: dockerbakery/github-metadata-action@v5
        with:
          token: ${{ secrets.github-token || github.token }}

      - if: ${{ inputs.permit-login }}
        name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.github-token || github.token }}

      - name: Build and push
        uses: docker/bake-action@v7
        with:
          allow: ${{ inputs.allow }}
          builder: ${{ inputs.builder }}
          call: ${{ inputs.call }}
          files: |
            ${{ inputs.files }}
            cwd://${{ steps.docker-meta.outputs.bake-file }}
            cwd://${{ steps.github-meta.outputs.bake-file }}
          load: ${{ inputs.load }}
          no-cache: ${{ inputs.no-cache }}
          provenance: ${{ inputs.provenance }}
          pull: ${{ inputs.pull }}
          push: ${{ inputs.permit-login && inputs.permit-push }}
          sbom: ${{ inputs.sbom }}
          set: |
            ${{ inputs.set }}
            ${{ inputs.permit-cache && '*.cache-from=type=gha' || ''}}
            ${{ inputs.permit-cache && '*.cache-to=type=gha,mode=min' || ''}}
          source: ${{ inputs.source }}
          targets: ${{ inputs.targets }}
          vars: ${{ inputs.vars }}
          github-token: ${{ secrets.BUILDX_BAKE_GIT_AUTH_TOKEN || secrets.github-token || github.token }}
